apiVersion: appli/v1
kind: Deployment
metadata:
  name: appli-deploy
  namespace: kube
  labels:
    app: appli
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appli
  template:
    metadata:
      name: 
      namespace: test
      labels:
        app: appli
    spec:
     containers:
     - name: appli
       image: di122/projetfinal
       command:
        - /usr/sbin/nginx
        - -g
        - daemon off;
        - -q
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
   
