--- 
- name: Install apache and configure web proxy  
  hosts: apache 
  become: True
  roles:
    - httpd 

- name: Install Jenkins 
  hosts: jenkins 
  become: True
  roles:
    - jenkins 

- name: Install Nexus 
  hosts: nexus 
  become: True
  roles:
    - nexus 

- name: Install Docker
  hosts: slave 
  become: True
  roles:
    - docker 
  tags:
    - docker

- name: Install Maven
  hosts: slave 
  become: True
  roles:
    - maven 
  tags:
    - maven
